-- ==============================================================================
-- COMPLETELY REPAIR/UPDATE DATABASE SCHEMA
-- Run this script to ensure all tables exist and are up to date.
-- ==============================================================================

-- 1. ENABLE EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. CREATE EMPLOYEES TABLE IF IT DOESN'T EXIST
CREATE TABLE IF NOT EXISTS employees (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  pin_hash TEXT NOT NULL, 
  role TEXT NOT NULL DEFAULT 'employee' CHECK (role IN ('employee', 'admin')),
  is_active BOOLEAN DEFAULT true,
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ADD NEW COLUMN (SAFE UPDATE)
-- This ensures the column exists even if the table was just created or already existed
ALTER TABLE employees ADD COLUMN IF NOT EXISTS pin_text TEXT;

-- 4. CREATE OTHER TABLES
CREATE TABLE IF NOT EXISTS time_entries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id UUID REFERENCES employees(id) ON DELETE CASCADE NOT NULL,
  start_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  end_time TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'break', 'completed')),
  start_location JSONB,
  end_location JSONB,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS breaks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  time_entry_id UUID REFERENCES time_entries(id) ON DELETE CASCADE NOT NULL,
  start_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  end_time TIMESTAMPTZ,
  reason TEXT
);

CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id UUID REFERENCES employees(id) ON DELETE CASCADE NOT NULL,
  time_entry_id UUID REFERENCES time_entries(id) ON DELETE CASCADE NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  accuracy DOUBLE PRECISION,
  heading DOUBLE PRECISION,
  speed DOUBLE PRECISION,
  battery_level INTEGER,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 5. ENABLE ROW LEVEL SECURITY
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE time_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE breaks ENABLE ROW LEVEL SECURITY;
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;

-- 6. POLICIES
DROP POLICY IF EXISTS "Allow read access for valid sessions" ON employees;
CREATE POLICY "Allow read access for valid sessions" ON employees FOR SELECT USING (true);

DROP POLICY IF EXISTS "Employees can insert their own entries" ON time_entries;
CREATE POLICY "Employees can insert their own entries" ON time_entries FOR INSERT WITH CHECK (employee_id = (current_setting('app.current_employee_id', true)::uuid));

DROP POLICY IF EXISTS "Employees can view own entries" ON time_entries;
CREATE POLICY "Employees can view own entries" ON time_entries FOR SELECT USING (employee_id = (current_setting('app.current_employee_id', true)::uuid));

DROP POLICY IF EXISTS "Employees can update own active entries" ON time_entries;
CREATE POLICY "Employees can update own active entries" ON time_entries FOR UPDATE USING (employee_id = (current_setting('app.current_employee_id', true)::uuid));

DROP POLICY IF EXISTS "Enable insert for active employees" ON locations;
CREATE POLICY "Enable insert for active employees" ON locations FOR INSERT WITH CHECK (true);

-- 7. UPDATE REGISTRATION FUNCTION (WITH PIN_TEXT)
CREATE OR REPLACE FUNCTION register_employee(
  p_first_name TEXT,
  p_last_name TEXT,
  p_pin TEXT,
  p_role TEXT DEFAULT 'employee'
)
RETURNS JSONB AS $$
DECLARE
  v_new_id UUID;
BEGIN
  INSERT INTO employees (first_name, last_name, pin_hash, pin_text, role)
  VALUES (
    p_first_name, 
    p_last_name, 
    crypt(p_pin, gen_salt('bf')), 
    p_pin, -- Store visible PIN
    p_role
  )
  RETURNING id INTO v_new_id;

  RETURN jsonb_build_object(
    'id', v_new_id,
    'first_name', p_first_name,
    'last_name', p_last_name,
    'role', p_role
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 8. LOGIN HELPER
CREATE OR REPLACE FUNCTION login_with_pin(p_pin TEXT)
RETURNS JSONB AS $$
DECLARE
  v_employee RECORD;
BEGIN
  FOR v_employee IN SELECT * FROM employees WHERE is_active = true LOOP
    IF v_employee.pin_hash = crypt(p_pin, v_employee.pin_hash) THEN
      RETURN jsonb_build_object(
        'id', v_employee.id,
        'first_name', v_employee.first_name,
        'last_name', v_employee.last_name,
        'role', v_employee.role
      );
    END IF;
  END LOOP;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
